baseURL: https://www.yellowbrickcode.co.uk/
languageCode: en-us
title: Yellow Brick Code
theme: hugo-fresh
enableRobotsTXT: true

permalinks:
  blog: /:title

params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: The road to better code
    # Hero subtitle (optional)
    subtitle: Need help with your architecture, code or culture? We can help.
    # Button text
    buttontext: See our services
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from /images/___)
    image: illustrations/toto_sit_1.svg
    # Footer logos (from /images/logos/clients/___.svg)
    
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Services
    url: /services
  - title: Blog
    url: /blog
  - title: About
    url: /about
  - title: Let's Talk
    url: /#contact
    button: true
  section1:
    title: Blog
    subtitle: Latest posts
    tiles:
    - title: App builder
      icon: mouse-globe
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Free trial
    - title: Cloud integration
      icon: laptop-cloud
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Get started
    - title: Add-ons & plugins
      icon: plug-cloud
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Get started
  section2:
    title: We want you to be the best you can be
    subtitle: Here are the highlights of how we can help
    features:
    - title: Cloud first architecture
      text: We're experienced with taking a cloud first approach to building architecture for enterprise level web applications
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Clean code
      text: Having clean, well written code isn't just for the developers working on it. It allows for quicker iterations and helps make your application more resilient
      icon: doc-sync
    - title: Building a forward thinking development culture
      text: We can help you develop a progressive culture that developers will enjoy working in
      icon: mobile-feed
  section3:
    title: One platform
    subtitle: To rule them all
    image: illustrations/mockups/app-mockup.png
    buttonText: Get started
    buttonLink: "#"
  section4:
    title: Our Clients love us!
    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    clients:
    - name: Irma Walters
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Accountant
      img: 1
    - name: John Bradley
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Financial Analyst
      img: 2
    - name: Gary Blackman
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: HR Manager
      img: 3
  footer:
    # Logo (from /images/logos/___)
    logo: Toto_sleep_1.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/yellowbrickcode
      # Icons are from Font Awesome
      icon: github
    - link: https://facebook.com/yellowbrickcodeltd
      icon: facebook
    - link: https://twitter.com/ff0brickcode
      icon: twitter
    - link: https://dev.to/yellowbrickcode
      icon: dev
    bulmalogo: false
    product:
    - text: Architecture
      link: /services#architecture
    - text: Development
      link: /services#development
    - text: Culture
      link: /services#culture
    docs:
    - text: People
      link: /about#people
    - text: Brains
      link: /about#brains
    - text: Heart
      link: /about#heart
    - text: Courage
      link: /about#courage
    blogroll:
    - text: Latest posts
      link: /blog